networks:
  1panel-network:
    external: true
      
services:
    axo-drive:
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        image: sfwwslm/vust-core:0.1.0-rc.1
        labels:
            createdBy: Apps
        volumes:
            - ./data:/data
        networks:
            - 1panel-network
        ports:
          - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:9990
          - ${HOST_IP}:${PANEL_APP_PORT_HTTPS}:9991
        environment:
          - TZ=Asia/Shanghai
        restart: always
